version: '3.9'

services:
  mysql_206:
    container_name: mysql_206
    hostname: mysql_206
    image: mysql:8.0.36
    restart: always

    env_file:
      - .env

    volumes:
      - mysql_206_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

    ports:
      - "3306:3306"
    

volumes:
  mysql_206_data: